# Generated by Django 4.1.13 on 2025-05-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='specialist_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoservice.services', verbose_name='Услуга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoservice.users', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoservice.services', verbose_name='Услуга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoservice.users', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialists',
            name='services',
            field=models.ManyToManyField(blank=True, to='autoservice.services', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoservice.specialists', verbose_name='Специалист'),
            preserve_default=False,
        ),
    ]
